DROP TABLE subprodutos;
DROP TABLE materiais_v_produtos;
DROP TABLE subvendas;
DROP TABLE vendas;
DROP TABLE pontos_venda;
DROP TABLE estoques;
DROP TABLE materiais;
DROP TABLE produtos;
DROP TABLE clientes;